# 1.9 – Structured Data: NumPy's Structured Arrays

While often our data can be well represented by a homogeneous array of values, sometimes this is not the case. This section demonstrates the use of NumPy's *structured arrays* and *record arrays*, which provide efficient storage for compound, heterogeneous data.  While the patterns shown here are useful for simple operations, scenarios like this often lend themselves to the use of Pandas ``Dataframe``s, which we'll explore in the next lecture.

In [1]:
import numpy as np

Imagine that we have several categories of data on a number of people (say, name, age, and weight), and we'd like to store these values for use in a Python program.
It would be possible to store these in three separate arrays:

In [2]:
name   = ['Alice', 'Bob', 'Cathy', 'Doug']
age    = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

But this is a bit clumsy. There's nothing here that tells us that the three arrays are related; it would be more natural if we could use a single structure to store all of this data.
NumPy can handle this through structured arrays, which are arrays with compound data types.

Recall that previously we created a simple array using an expression like this:

In [3]:
x = np.zeros(4, dtype=int)

We can similarly create a structured array using a compound data type specification:

In [4]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data,"\n")
print(data.dtype)

[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)] 

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


Here ``'U10'`` translates to "Unicode string of maximum length 10," ``'i4'`` translates to "4-byte (i.e., 32 bit) integer," and ``'f8'`` translates to "8-byte (i.e., 64 bit) float."
We'll discuss other options for these type codes in the following section.

Now that we've created an empty container array, we can fill the array with our lists of values:

In [5]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


As we had hoped, the data is now arranged together in one convenient block of memory.

The handy thing with structured arrays is that you can now refer to values either by index or by name:

In [6]:
# Get all names
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [7]:
# Get first row of data
data[0]

('Alice', 25, 55.)

In [8]:
# Get the name from the last row
data[-1]['name']

'Doug'

Using Boolean masking, this even allows you to do some more sophisticated operations such as filtering on age:

In [9]:
# Get names where age is under 30
data[data['age'] < 30]['age']

array([25, 19], dtype=int32)

Sorting and partitioning:

In [10]:
# Sort by age, then name, if ages are equal
np.sort(data, order=['age', 'name'])

array([('Doug', 19, 61.5), ('Alice', 25, 55. ), ('Cathy', 37, 68. ),
       ('Bob', 45, 85.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [11]:
# Partition by weight
np.partition(data, 2, order=['weight'])

array([('Alice', 25, 55. ), ('Doug', 19, 61.5), ('Cathy', 37, 68. ),
       ('Bob', 45, 85.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

Note that if you'd like to do any operations that are any more complicated than these, you should probably consider the Pandas package, covered in the next chapter.
As we'll see, Pandas provides a ``Dataframe`` object, which is a structure built on NumPy arrays that offers a variety of useful data manipulation functionality similar to what we've shown here, as well as much, much more.

## Creating Structured Arrays

Structured array data types can be specified in a number of ways.
Earlier, we saw the dictionary method:

In [12]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

For clarity, numerical types can be specified using Python types or NumPy ``dtype``s instead:

In [13]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

A compound type can also be specified as a list of tuples:

In [14]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

If the names of the types do not matter to you, you can specify the types alone in a comma-separated string:

In [15]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

The shortened string format codes may seem confusing, but they are built on simple principles.
The first (optional) character is ``<`` or ``>``, which means "little endian" or "big endian," respectively, and specifies the ordering convention for significant bits.
The next character specifies the type of data: characters, bytes, ints, floating points, and so on (see the table below).
The last character or characters represents the size of the object in bytes.

| Character        | Description           | Example                             |
| ---------        | -----------           | -------                             | 
| ``'b'``          | Byte                  | ``np.dtype('b')``                   |
| ``'i'``          | Signed integer        | ``np.dtype('i4') == np.int32``      |
| ``'u'``          | Unsigned integer      | ``np.dtype('u1') == np.uint8``      |
| ``'f'``          | Floating point        | ``np.dtype('f8') == np.int64``      |
| ``'c'``          | Complex floating point| ``np.dtype('c16') == np.complex128``|
| ``'S'``, ``'a'`` | String                | ``np.dtype('S5')``                  |
| ``'U'``          | Unicode string        | ``np.dtype('U') == np.str_``        |
| ``'V'``          | Raw data (void)       | ``np.dtype('V') == np.void``        |

**Your turn.** Create a structured array ``cities`` using a compound data type specification:
``(city:U15, capital:bool_, population:uint32)`` and containing the following records:
```
London,   True,  8982000
Hatfield, False,   32000
```

In [1]:
# write your code here



Append the ``cities`` array with the following record:
```
St. Albans, False, 58000
```
**Important!** Numpy arrays are non-dynamical objects. To add a new record you need to create a new array that contains old and new records. For instance,
```
new_array = np.append(old_array, new_data)
```

In [2]:
# write your code here



## More Advanced Compound Types

It is possible to define even more advanced compound types.
For example, you can create a type where each element contains an array or matrix of values.
Here, we'll create a data type with a ``mat`` component consisting of a $3\times 3$ floating-point matrix:

In [18]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X  = np.zeros(2, dtype=tp)
print(X, "\n")
print(X['mat'][0])

[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
 (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Now each element in the ``X`` array consists of an ``id`` and a $3\times 3$ matrix.
Why would you use this rather than a simple multidimensional array, or perhaps a Python dictionary?
The reason is that this NumPy ``dtype`` directly maps onto a C structure definition, so the buffer containing the array content can be accessed directly within an appropriately written C program.
If you find yourself writing a Python interface to a legacy C or Fortran library that manipulates structured data, you'll probably find structured arrays quite useful!

**Your turn.** Create a three component strutured array ``countries`` such that each component contains the name of a country and a 3-dimensional array of cities. Then populate this array with the three countries of Great Britain and three cities of each country.

In [3]:
# write your code here



## RecordArrays: Structured Arrays with a Twist

NumPy also provides the ``np.recarray`` class, which is almost identical to the structured arrays just described, but with one additional feature: fields can be accessed as attributes rather than as dictionary keys.
Recall that we previously accessed the ages by writing:

In [20]:
data['age']

array([25, 45, 37, 19], dtype=int32)

If we view our data as a record array instead, we can access this with slightly fewer keystrokes:

In [21]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19], dtype=int32)

The downside is that for record arrays, there is some extra overhead involved in accessing the fields, even when using the same syntax. We can see this here:

In [22]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

45 ns ± 0.174 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
816 ns ± 1.35 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.31 µs ± 1.24 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Whether the more convenient notation is worth the additional overhead will depend on your own application.

## On to Pandas

This section on structured and record arrays is purposely at the end of this chapter, because it leads so well into the next package we will cover: Pandas.
Structured arrays like the ones discussed here are good to know about for certain situations, especially in case you're using NumPy arrays to map onto binary data formats in C, Fortran, or another language.
For day-to-day use of structured data, the Pandas package is a much better choice, and we'll dive into a full discussion of it in the next lecture.

## Bonus Exercise

The [Collatz](https://en.wikipedia.org/wiki/Collatz_conjecture) conjecture in mathematics asks whether repeating certain simple arithmetic operations will eventually transform every positive integer into one. It concerns sequences of integers in which each term is obtained from the previous term as follows: if the previous term is even, the next term is one half of the previous term. If the previous term is odd, the next term is 3 times the previous term plus 1. In other words,

$$
x_{n+1} = \begin{cases} \frac{1}{2}x_n & \text{ if $x_n$ is even} \\ 3x_n +1 & \text{ if $x_n$ is odd} \end{cases}
$$

The conjecture is that these sequences always reach 1, no matter which positive integer is chosen to start the sequence. For instance,

$$
x_0 = 5, \; x_1 = 16, \; x_2 = 8,\; x_3 = 4,\; x_4 = 2,\; x_5 = 1
$$

The first few Collatz sequences are shown below. ![Collatz](figures/collatz.png)


The number of iterations it takes to get to 1 is called the total stopping time. The maximum value the sequence reaches is called the height of the sequence. For instance, the sequence starting at $x_0=5$ has the total stopping time equal to 5 and its height is 16.


This conjecture is extraordinarily difficult, and is believed to be completely out of reach of present day mathematics. As of 2020, it has been verified by computer for all starting values up to $2^{68} \approx 2.95\times10^{20}$.

- Reproduce the plot above

- Find the total stopping times and the heights of the first 10,000 (or 100,000, or 1000,000) sequences

- Plot the total stopping times versus starting values ([example](https://en.wikipedia.org/wiki/File:Collatz_Conjecture_100M.jpg))

- Plot heights versus starting values; use ``plt.ylim(bottom, top)`` to restrict y values, since some heights are much higher that the rest ([example](https://en.wikipedia.org/wiki/Collatz_conjecture#/media/File:CollatzConjectureGraphMaxValues.jpg))

You will see interesting patterns that even the brightest minds on our planet struggle to understand. 
I suggest watching this [YouTube video](https://www.youtube.com/watch?v=094y1Z2wpJg) to learn more about this mind-boggling problem.

In [23]:
# write your solutions here



---

<!--NAVIGATION-->
< [1.8 – Sorting Arrays](L18_Sorting.ipynb) | [Contents](../index.ipynb) | [2.1 – Intro to Pandas](L21_Intro_to_Pandas.ipynb) >

*This notebook contains an excerpt from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) by Jake VanderPlas; also available [on GitHub](https://github.com/jakevdp/PythonDataScienceHandbook).*